import Link from 'next/link';
import { useState } from 'react';

import type { Metadata } from "next";
import localFont from "next/font/local";
import GoogleAnalytics from './GoogleAnalytics';
import GoogleTagManager from './GoogleTagManager';
import "./globals.css";
import { Inter, Merriweather, Roboto, Fira_Sans, PT_Serif } from 'next/font/google';
import Image from 'next/image';
import './globals.css'
import ScrollButtons from './ScrollButtons'
import { Analytics } from "@vercel/analytics/react"
import Script from 'next/script';
import Header from './components/Header';
import HotjarAnalytics from './HotjarAnalytics';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const firaSans = Fira_Sans({ weight: ['400', '700', '900'], subsets: ['latin'], display: 'swap', variable: '--font-fira-sans' })
const ptSerif = PT_Serif({ weight: ['400', '700'], subsets: ['latin'], display: 'swap', variable: '--font-pt-serif' })
const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'], display: 'swap', variable: '--font-roboto' })
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const merriweather = Merriweather({ weight: '400', subsets: ['latin'], variable: '--font-merriweather' })

export const metadata: Metadata = {
  title: "Urantia Book Podcast",
  description: "A NotebookLM-powered podcast exploring the Urantia Book.",
};

// Replace this with your actual Google Analytics Measurement ID
const GA_MEASUREMENT_ID = 'GTM-T3B4GTDJ'

// Add this with your other constants
const HOTJAR_ID = '5205817'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${firaSans.variable} ${ptSerif.variable}`}>
      <GoogleTagManager gtmId="GTM-T3B4GTDJ" />
      <body className="bg-light font-sans text-gray-900">
        {/* Google Tag Manager (noscript) */}
        <noscript>
        <iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-T3B4GTDJ"
          height="0"
          width="0"
          style={{ display: 'none', visibility: 'hidden' }}
        />
      </noscript>
    <Header />
    <main className="container mx-auto px-4 py-8 flex-grow">
      {children}
    </main>
    <footer className="bg-dark text-white mt-8">
      <div className="container mx-auto px-4 py-6 text-center">
        <p className="mb-4 text-sm">
          This podcast content was generated by{' '}
          <Link href="https://notebooklm.google.com/" className="text-primary hover:text-primary-light underline" target="_blank" rel="noopener noreferrer">
            NotebookLM
          </Link>
          , using <i>The Urantia Papers</i> as the sole source material.<br></br> The audio narration is AI-generated and may not perfectly reflect human intonation or pronunciation.
        </p>
        <div className="mb-4">
          <Link 
            href="/disclaimer" 
            target="_blank" 
            rel="noopener noreferrer" 
            className="inline-block bg-gray-700 hover:bg-gray-600 text-white px-4 py-2 rounded-md font-medium transition duration-300"
          >
            Read Full Disclaimer
          </Link>
        </div>
        <p className="mb-2">© 2024 The Center for Unity. All rights reserved.</p>
        <p className="mb-4">
          Urantia Book Podcast is a project by{' '}
          <Link href="https://www.thecenterforunity.org" className="text-primary hover:text-primary-light underline" target="_blank" rel="noopener noreferrer">
            The Center for Unity
          </Link>
          .
        </p>
      </div>
    </footer>
    <ScrollButtons />
    <GoogleAnalytics GA_MEASUREMENT_ID={GA_MEASUREMENT_ID} />
    <HotjarAnalytics HOTJAR_ID={HOTJAR_ID} />
    <Analytics />

     {/* OptinMonster Script */}
     <Script id="optinmonster-script" strategy="afterInteractive">
      {`
        (function(d,u,ac){
          var s=d.createElement('script');
          s.type='text/javascript';
          s.src='https://a.omappapi.com/app/js/api.min.js';
          s.async=true;
          s.dataset.user=u;
          s.dataset.account=ac;
          d.getElementsByTagName('head')[0].appendChild(s);
        })(document,345457,365360);
      `}
    </Script>
  </body>
</html>
  )
}
